### ISSUE TITLE
Failed to load configurations: Error Domain=NEConfigurationErrorDomain Code=10 "permission denied" UserInfo={NSLocalizedDescription=permission denied}

### ISSUE THREAD

**Issue by scratchi7777** [nizwar/openvpn_flutter#115]
Please help!(
flutter: The Dart VM service is listening on http://127.0.0.1:56575/jlgnsW2wlRE=/
 Failed to load configurations: Error Domain=NEConfigurationErrorDomain Code=10 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-4, permission denied, permission denied, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      OpenVPN.initialize.<anonymous closure> (package:openvpn_flutter/src/vpn_engine.dart:108:13)
<asynchronous suspension>

**Comment by scratchi7777** [comment]
Run on IOS, but I clicked Connect button got this error!
