### ISSUE TITLE
I have a problem in building iOS with openvpn_flutter repository.

### ISSUE THREAD

**Issue by easytem-vpn** [nizwar/openvpn_flutter#126]
I am building OpenVPN app based on openvpn_flutter.
Android version works well.
But for iOS version, I am stuck.
When I build it, cyclic inside runner

Please help me!!!

here is error details.

Showing Recent Errors Only
Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner' has copy command from '/Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/VPNExtension.appex' to '/Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/VPNExtension.appex'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/VPNExtension.appex' to '/Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/VPNExtension.appex'

Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/ExtractedAppShortcutsMetadata.stringsdata ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftConstValuesFileList ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftConstValuesFileList ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7--cp--copy-pods-resources> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7--cp--copy-pods-resources ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-32E4D19BF3566242286EA254-Pods-Runner-resources-Debug-input-files-5a14f3ff887fd85480de18560a23ad8f-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-32E4D19BF3566242286EA254-Pods-Runner-resources-Debug-input-files-5a14f3ff887fd85480de18560a23ad8f-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--embed-pods-frameworks ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-583F2B9532AD9155482EAB7C-Pods-Runner-frameworks-Debug-input-files-d1a7f885d1cb4f8f7f9b1ef7e041ce98-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-583F2B9532AD9155482EAB7C-Pods-Runner-frameworks-Debug-input-files-d1a7f885d1cb4f8f7f9b1ef7e041ce98-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5-copy-files> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5-copy-files ->

node: <Copy /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/VPNExtension.appex> ->

CYCLE POINT ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/VPNExtension.appex /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/VPNExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist/ ->

directoryTreeSignature: � ->

directoryContents: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist /Users/flash/Desktop/easytem-mobile/easytem/ios/Runner/Info.plist ->

node: /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/VPNExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/VPNExtension.appex /Users/flash/Library/Developer/Xcode/DerivedData/Runner-ehnykkgyoptkxpfgduakcevbhkwb/Build/Products/Debug-iphonesimulator/VPNExtension.appex

**Comment by Who-Code** [comment]
also no way getting it run for ios:

After integrating all the changes and running the pod install command i get the following error:

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["B15FB5E92D2EC11D002AF878"], "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"VPNExtension", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'`
```

What helped me was doing the solution of:
https://github.com/CocoaPods/CocoaPods/issues/12456#issuecomment-2277024800

I rightclicked the VPNExtension Folder in XCode of my Runner and then selected convert to group.
Pod install now worked

**Comment by manukeepgoing** [comment]
Hi there, 

I was facing this issue when I found this post on stackoverflow that might help. As is said on the post, maybe does not work for everyone, but at least it works for me also. Give it a try and tell me if it works for you also. 

https://stackoverflow.com/questions/77138968/handling-cycle-inside-runner-building-could-produce-unreliable-results-after-up

Good luck.

**Comment by shahmeer1124** [comment]
Arranging build phase like this solved this issue for me

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/1730165e-ef5c-4fc3-8c54-7b5b7736397a" />
