### ISSUE TITLE
Android VPNStage.unknown problem

### ISSUE THREAD

**Issue by Borzalic** [nizwar/openvpn_flutter#70]
Hi,

`I/OpenVPN (28832): Starting openvpn
I/OpenVPN (28832): /data/app/~~s5-TVM_32zHZabmaPobNOw==/com.example-8P-85jmdnpkEsLE8Y4zWYw==/lib/arm64:/data/app/~~s5-TVM_32zHZabmaPobNOw==/com.example-8P-85jmdnpkEsLE8Y4zWYw==/lib/arm64/libovpnexec.so
15
I/flutter (28832): VPNSTATUS: {connected_on: null, duration: 00:00:00, byte_in: 0, byte_out: 0, packets_in: 0, packets_out: 0}`

The VPNSTATUS line keeps looping. Its ok for IOS but stucking on Android.

**Comment by TheRangerStar** [comment]
> Hi,
> 
> `I/OpenVPN (28832): Starting openvpn I/OpenVPN (28832): /data/app/~~s5-TVM_32zHZabmaPobNOw==/com.example-8P-85jmdnpkEsLE8Y4zWYw==/lib/arm64:/data/app/~~s5-TVM_32zHZabmaPobNOw==/com.example-8P-85jmdnpkEsLE8Y4zWYw==/lib/arm64/libovpnexec.so 15 I/flutter (28832): VPNSTATUS: {connected_on: null, duration: 00:00:00, byte_in: 0, byte_out: 0, packets_in: 0, packets_out: 0}`
> 
> The VPNSTATUS line keeps looping. Its ok for IOS but stucking on Android.

I don't understand why IOS always returns 0.
Can you help me? Because you say IOS is normal.
Why?
![image](https://user-images.githubusercontent.com/55529715/222382808-fd9d68de-e7fd-4d3c-82d2-7d3999d87c46.png)

**Comment by trongbudop113** [comment]
Hi, I have an issue
When I install app then I turn on VPN, App will show dialog, I click OK and crash app. I launch app a again, crashes no more.
Log Error:
`E/AndroidRuntime(26212): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=24, result=0, data=null} to activity {com.concung.ccapp.erp.uat/com.concung.ccapp.erp.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
E/AndroidRuntime(26212): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5239)
E/AndroidRuntime(26212): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5280)
E/AndroidRuntime(26212): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(26212): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(26212): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(26212): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
E/AndroidRuntime(26212): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26212): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(26212): 	at android.app.ActivityThread.main(ActivityThread.java:8163)
E/AndroidRuntime(26212): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26212): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(26212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(26212): Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
E/AndroidRuntime(26212): 	at com.concung.ccapp.erp.MainActivity.onActivityResult(Unknown Source:2)
E/AndroidRuntime(26212): 	at android.app.Activity.dispatchActivityResult(Activity.java:8511)
E/AndroidRuntime(26212): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5232)
E/AndroidRuntime(26212): 	... 11 more`

**Comment by kashiflab** [comment]
I am also facing the same issue @nizwar Can you please take a look into this
